export const AppStrings = {
  common: {
    retry: 'Retry',
    somethingWentWrong: 'Something went wrong',
    delete: 'Delete',
    logout: 'Logout',
    cancel: 'Cancel',
    save: 'Save',
  },
  splash: {
    appName: 'TaskFlow',
    tagline: 'Stay organized, stay ahead',
  },
  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to your account',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailPlaceholder: 'you@example.com',
    passwordPlaceholder: '••••••••',
    loginButton: 'Sign In',
    registerPrompt: "Don't have an account? Sign up",
  },
  register: {
    title: 'Create account',
    subtitle: 'Sign up to get started',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailPlaceholder: 'you@example.com',
    passwordPlaceholder: '••••••••',
    registerButton: 'Sign Up',
    loginPrompt: 'Already have an account? Login',
  },
  taskList: {
    greeting: 'Good morning 👋',
    sectionLabel: 'My Tasks',
    statTotal: 'Total',
    statDone: 'Done',
    emptyTitle: 'No tasks yet',
    emptySubtitle: 'Tap + to add your first task',
    addPlaceholder: 'Add a new task...',
  },
  editModal: {
    title: 'Edit task',
  },
};
