export const AppStrings = {
  common: {
    retry: 'Retry',
    somethingWentWrong: 'Something went wrong',
    delete: 'Delete',
    logout: 'Logout',
    cancel: 'Cancel',
    save: 'Save',
    add: 'Add',
  },
  brand: 'TaskFlow',
  login: {
    title: 'Welcome back',
    subtitle: 'Sign in to continue',
    registerTitle: 'Create account',
    registerSubtitle: 'Sign up to get started',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailPlaceholder: 'you@example.com',
    passwordPlaceholder: '••••••••',
    loginButton: 'Sign In',
    registerButton: 'Sign Up',
    toRegister: "Don't have an account? Sign up",
    toLogin: 'Already have an account? Login',
  },
  taskList: {
    greeting: 'Good morning 👋',
    sectionLabel: 'My Tasks',
    statTotal: 'Total',
    statDone: 'Done',
    emptyTitle: 'No tasks yet',
    emptySubtitle: 'Add one above ↑',
    addPlaceholder: 'Add a new task...',
  },
  editModal: {
    title: 'Edit task',
  },
};
